language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
  - COMPOSER_ROOT_VERSION=dev-master composer install --dev --prefer-source

notifications:
  email: false
  irc:
    channels:
      - "irc.freenode.org#lonelypullrequests"
    use_notice: true

script: phpunit --coverage-clover=coverage.clover

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
