LonelyPullRequests\Domain\PullRequest:
  type: entity
  repositoryClass: LonelyPullRequests\Infrastructure\Persistence\DoctrinePullRequestsRepository
  table: pullrequest
  readOnly: false
  indexes:
    name_index:
      columns: [ repositoryName, title ]
  id:
    repositoryName:
      type: repositoryName
      length: 255
    title:
      type: title
      length: 255
  fields:
    url:
      type: url
      length: 255
    loneliness:
      type: loneliness
      length: 8