services:
    lonely_pull_requests.repository.pull_requests:
        class: LonelyPullRequests\Infrastructure\Persistence\DoctrinePullRequestsRepository
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments: [LonelyPullRequests\Domain\PullRequest]
    lonely_pull_requests.repository.notification:
        class: LonelyPullRequests\Infrastructure\Persistence\GithubNotificationRepository
        arguments: ['%github_api_key%']
